# USER ERROR MESSAGE

NO_USER_WITH_THAT_ID_ERROR = 'NO USER PRESENT WITH THAT ID'
USER_ADDED_SUCCESSFULLY = 'USER ADDED SUCCESSFULLY'
WORKING_UNDER_IS_NOT_A_SUPERVISOR = 'THE USER UNDER WHICH YOU ARE ASSIGNING THE CURRENT USER IS NOT A SUPERVISOR'
WORKING_UNDER_IS_NOT_A_ADMIN = 'THE USER UNDER WHICH YOU ARE ASSIGNING THE CURRENT USER IS NOT A ADMIN'
INVALID_ROLE_ERROR = 'GIVEN ROLE IS INVALID'
UPDATED_USER_SUCCESSFULLY = 'UPDATED USER SUCCESSFULLY'
EMAIL_NOT_FOUND = 'EMAIL IS NOT REGISTERED WITH US'
PROCESSING_ERROR = 'PROCESSING ERROR'

# COMPANY ERROR MESSAGE

COMPANY_ADDED_SUCCESSFULLY = 'COMPANY ADDED SUCCESSFULLY'
COMPANY_DELETED_SUCCESSFULLY = 'COMPANY DELETED SUCCESSFULLY'