# USER ERROR MESSAGE

NO_USER_WITH_THAT_ID_ERROR = 'NO USER PRESENT WITH THAT ID'
USER_ADDED_SUCCESSFULLY = 'USER ADDED SUCCESSFULLY'
WORKING_UNDER_IS_NOT_A_SUPERVISOR = 'THE USER UNDER WHICH YOU ARE ASSIGNING THE CURRENT USER IS NOT A SUPERVISOR'
WORKING_UNDER_IS_NOT_A_ADMIN = 'THE USER UNDER WHICH YOU ARE ASSIGNING THE CURRENT USER IS NOT A ADMIN'
INVALID_ROLE_ERROR = 'GIVEN ROLE IS INVALID'
UPDATED_USER_SUCCESSFULLY = 'UPDATED USER SUCCESSFULLY'
EMAIL_NOT_FOUND = 'EMAIL IS NOT REGISTERED WITH US'
EMAIL_FOUND = 'EMAIL IS REGISTERED WITH US'
USER_IS_NOT_REGISTERED_WITH_US = 'USER IS NOT REGISTERED WITH US'
USER_IS_ALREADY_REGISTERED_WITH_US = 'USER IS ALREADY REGISTERED WITH US'
PROCESSING_ERROR = 'PROCESSING ERROR'
INVALID_CREDENTIALS = 'INVALID CREDENTIALS'
USER_IS_INACTIVE = 'USER IS DELETED PLEASE CONTACT ADMIN'
USER_IS_UNAUTHORISED = 'YOU ARE NOT AUTHORIZED TO PERFORM THIS OPERATION'
USER_NOT_FOUND = 'USER NOT FOUND'
USER_DOES_NOT_WORK_UNDER_YOUR_COMPANY = 'USER DOES NOT WORK FOR YOUR COMPANY'

# COMPANY ERROR MESSAGE

COMPANY_ADDED_SUCCESSFULLY = 'COMPANY ADDED SUCCESSFULLY'
COMPANY_UPDATED_SUCCESSFULLY = 'COMPANY UPDATED SUCCESSFULLY'
COMPANY_DELETED_SUCCESSFULLY = 'COMPANY DELETED SUCCESSFULLY'
COMPANY_ALREADY_REGISTERED = 'COMPANY WITH SAME NAME ALREADY REGISTERED'
ADDING_ERROR = 'UNABLE TO ADD RIGHNOW'
COMPANY_NOT_FOUND = 'COMPANY NOT FOUND'
 
# TOKEN ERROR

TOKEN_INVALID = 'TOKEN INVALID'